
# camera_name: "hikrobot"
# exposure_ms: 10
# gain: 16
# vid_pid: "2bdf:0001"

camera_name: "dahengvision"
exposure_ms: 20  # 曝光时间(毫秒)
gamma: 1      # 伽马值
vid_pid: "2ba2:4d55"  # 大恒相机的VID:PID，可通过 `lsusb` 命令查看
